forcedotcom/lwc-dev-mobile

src/common/AndroidEnvironmentSetup.ts, src/common/AndroidUtils.ts
Before: 
After:
Before:
After:
Before:
After:
Before:
After:
=> Error Messaging Cleanup

.vscode/launch.json, messages/device.json, src/cli/commands/force/lightning/local/device/__tests__/list.test.ts, src/cli/commands/force/lightning/local/device/list.ts, src/cli/commands/force/lightning/local/setup.ts, src/cli/commands/force/lightning/lwc/__tests__/preview.test.ts, src/cli/commands/force/lightning/lwc/preview.ts, src/common/AndroidTypes.ts, src/common/AndroidUtils.ts, src/common/IOSLauncher.ts, src/common/IOSTypes.ts, src/common/IOSUtils.ts
Adds support for a new sfdx command: `force:lightning:local:device:list -p [iOS|Android]`
=> Add new device list command

package.json, yarn.lock
Should remove the yaml dependency as well which is causing the dependabot security issue.
=> Removes salesforce-jest dependency for tests

src/common/AndroidUtils.ts, src/common/__tests__/AndroidUtils.test.ts
In addition I have created a new functions to read/write AVD config as a list of key/value pairs.  Devices are now created with proper skins, tested on Pixel, Pixel XL and Pixel C but should work on any device.  A brief look into how we generate AVD's for Pixel 2/3/etc did not yield any quick wins so I left supported devices unchanged.
=> Update AVD config to create better emulators.

yarn.lock
Merging changes from https://github.com/forcedotcom/lwc-dev-mobile/pull/60.
=> Merge-back: master to dev

src/cli/commands/force/lightning/local/device/list.ts, src/common/PerformanceMarkers.ts, src/common/Requirements.ts
Update Setup and DeviceList commands to compute execution time for each requirement check as well as overall execution time for the commands.
=> compute execution time of requirements

src/common/AndroidUtils.ts
We currently determine whether an emulator is running (via AndroidUtils.isEmulatorAlreadyStarted()) by checking for the existence of a "magic" file. If that file exists then we assume that the emulator is running and we won't proceed with launching the emulator (instead we'll just try to connect to it to preview LWC components).
However if an emulator does not shut down gracefully for whatever reason, then that magic file can be left behind even though the emulator is not running. Now we've gotten to a state where we cannot preview any components on that emulator b/c we keep thinking that it is already running when it really is not.
This PR updates the code so that in addition to checking for the magic file we also check to see if the emulator process is running.
=> Determine if emulator is running by checking its process too

messages/setup.json, package.json, src/common/AndroidUtils.ts, src/common/IOSEnvironmentSetup.ts, src/common/IOSUtils.ts, src/common/__tests__/AndroidMockData.ts, src/common/__tests__/AndroidUtils.test.ts, src/config/androidconfig.json, src/config/iosconfig.json
Supporting iOS 14(.x) and Android 30 (R).
=> Adding support for latest Android/iOS SDKs

src/common/AndroidUtils.ts
Currently the setup command picks the latest available Android API package installed on the user's machine regardless of whether it has matching emulator images or not. It is possible for a user to have multiple API packages installed on their machine and have emulator images for only some of them.
This PR adds the ability to find/use the latest API package that also has matching emulator images.
=> pick pkg with matching emulator images

package.json
=> Rev'ing package version, contributors info, etc.

src/common/AndroidUtils.ts
This PR reverts a few changes that were made in #89 and adds some comment about why it is necessary for things to be this way, so that in the future we don't break this.
=> revert spawning changes for starting emulators

.vscode/launch.json, messages/devicecreate.json, messages/devicelist.json, src/cli/commands/force/lightning/local/device/__tests__/create.test.ts, src/cli/commands/force/lightning/local/device/__tests__/list.test.ts, src/cli/commands/force/lightning/local/device/create.ts, src/cli/commands/force/lightning/local/device/list.ts, src/cli/commands/force/lightning/lwc/__tests__/preview.test.ts, src/cli/commands/force/lightning/lwc/preview.ts, src/common/AndroidEnvironmentSetup.ts, src/common/CommonUtils.ts, src/common/IOSEnvironmentSetup.ts, src/common/Requirements.ts, src/common/__tests__/AndroidEnvironmentSetup.test.ts, src/common/__tests__/IOSEnvironmentSetup.test.ts, src/common/__tests__/Requirements.test.ts
This PR adds the ability to create iOS/Android simulator/emulator devices using sfdx device create command.
=> Add Device Create command

src/cli/commands/force/lightning/local/device/__tests__/create.test.ts, src/cli/commands/force/lightning/local/device/create.ts, src/cli/commands/force/lightning/local/device/list.ts, src/cli/commands/force/lightning/lwc/preview.ts
Use CLI start/stop functions in `CommonUtils` for our commands to indicated progress.
=> updated commands to report action stages

.circleci/config.yml, package.json, src/cli/commands/force/lightning/lwc/__tests__/preview.test.ts, yarn.lock
Ensure we build + run tests on Windows platform too.
=> Enable Windows builds on CircleCI

package.json, yarn.lock
Consumes the beta channel lwc-dev-mobile-core package.
=> Beta testing integration with lwc-dev-mobile-core

src/cli/commands/force/lightning/local/__tests__/setup.test.ts, src/cli/commands/force/lightning/local/device/__tests__/create.test.ts, src/cli/commands/force/lightning/local/device/__tests__/list.test.ts, src/cli/commands/force/lightning/local/device/list.ts, src/cli/commands/force/lightning/local/setup.ts, src/cli/commands/force/lightning/lwc/__tests__/preview.test.ts, src/cli/commands/force/lightning/lwc/preview.ts
Increase test/code coverage by adding useful tests.
=> Add more unit tests

package.json, src/cli/commands/force/lightning/__tests__/setupRequirementsUtil.test.ts, src/cli/commands/force/lightning/local/__tests__/setup.test.ts, src/cli/commands/force/lightning/local/device/__tests__/create.test.ts, src/cli/commands/force/lightning/local/device/__tests__/list.test.ts, src/cli/commands/force/lightning/local/device/__tests__/start.test.ts, src/cli/commands/force/lightning/local/device/create.ts, src/cli/commands/force/lightning/local/device/list.ts, src/cli/commands/force/lightning/local/device/start.ts, src/cli/commands/force/lightning/local/setup.ts, src/cli/commands/force/lightning/lwc/__tests__/preview.test.ts, src/cli/commands/force/lightning/lwc/preview.ts, src/cli/commands/force/lightning/setupRequirementsUtil.ts, yarn.lock
Incorporating the refactor done in the `core` lib into public commands.
=> @W-8888184 - Refactor public commands.

package.json, yarn.lock
This 1.2.0 RC captures the dev changes merged from https://github.com/forcedotcom/lwc-dev-mobile/pull/120.
=> lwc-dev-mobile 1.2.0 Release Candidate

README.md
=> Updated link to localdev page.

README.md
@maliroteh-sf Updating another reference.
=> Updating another location referencing localdev.
